### ISSUE TITLE
How to get this working in NextJS?

### ISSUE THREAD

**Issue by SaadBazaz** [hyperbrew/bolt-cep#111]
I'm building a project in NextJS and would love to have bolt working there, because it makes all work a breeze. Will need to write everything in just NextJS and it'll work for Adobe. 

Is there any way we can get this to work, or if it **does** work through some configuration, we could perhaps write it down?

**Comment by justintaylor-dev** [comment]
NextJS is a totally different stack than Vite, so that's beyond the scope of Bolt CEP. It would require a major reworking and since CEP panels are local and SSR isn't as important as the web.

If you wanted to build an implementation yourself, you'd likely need 2 extension panels, one headless to act as the backend and one as the frontend and set them up to communicate over CEP channels rather than Next API endpoints.
