### ISSUE TITLE
AE 2025 Compatibility

### ISSUE THREAD

**Issue by SteveLewisZA** [hyperbrew/bolt-cep#136]
Hey there,

It appears that any extension panel built with the boilerplate does not start up at all when launching in AE 2025, steps to reproduce:

- Create a new demo extension with the boilderplate (I used Vue)
- Build the extension
- Run it via Window > Extensions
- Nothing happens, no panel opens, no errors

Perhaps it's related to a passing bug that Adobe may resolve soon? Otherwise may be worth looking at, as I do see that other extensions run correctly.

Thanks!
Steve

**Comment by Jorgenious** [comment]
I had the same issue, after updating AE to the 2025 version. It seems that there's an update in the App data generated by adobe, from CSXS.11 to CSXS.12. After running this command (on Mac) the issue was gone

`defaults write /Users/<username>/Library/Preferences/com.adobe.CSXS.12.plist PlayerDebugMode 1`

**Comment by SteveLewisZA** [comment]
@Jorgenious Ah I see, thanks!

On Windows I see it's a case of opening regedit and adding `PlayerDebugMode` with value `1` to `Computer\HKEY_CURRENT_USER\Software\Adobe\CSXS.12`

**Comment by Ligerx** [comment]
I also ran into this today when trying to get up and running. Is it something that can be added to the readme?
