### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by fartinmartin** [hyperbrew/bolt-cep#20]
Looks like this is a [Windows/Mac line ending issue](https://stackoverflow.com/questions/30344858/node-script-executable-not-working-on-mac-env-node-r-no-such-file-or-directo), but not sure exactly how to fix this.

```
yarn create bolt-cep my-app --template react
yarn create v1.22.17
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
warning "create-bolt-cep > ts-node@10.7.0" has unmet peer dependency "@types/node@*".
[4/4] 🔨  Building fresh packages...

success Installed "create-bolt-cep@0.1.9" with binaries:
      - create-bolt-cep
env: node\r: No such file or directory
error Command failed.
Exit code: 127
Command: /Users/Martin/.yarn/bin/create-bolt-cep
Arguments: my-app --template react
Directory: /Users/Martin/dev
Output:

info Visit https://yarnpkg.com/en/docs/cli/create for documentation about this command.
```

**Comment by justintaylor-dev** [comment]
Are you using Node 16 or above?

**Comment by fartinmartin** [comment]
Yeah, `v16.13.0`

**Comment by justintaylor-dev** [comment]
What OS and version are you on?

**Comment by fartinmartin** [comment]
`npx envinfo --system --binaries` output:

```
System:
  OS: macOS 12.3
  CPU: (8) arm64 Apple M1
  Memory: 2.23 GB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.13.0 - ~/.nvm/versions/node/v16.13.0/bin/node
  Yarn: 1.22.17 - /opt/homebrew/bin/yarn
  npm: 8.5.2 - ~/.nvm/versions/node/v16.13.0/bin/npm
```

Worried it may be an M1 thing, I tested the same `yarn create ...` command and got the same error on another machine with this `npx envinfo --system --binaries` output:

```
System:
  OS: macOS 12.3.1
  CPU: (12) x64 Intel(R) Core(TM) i7-9750H CPU @ 2.60GHz
  Memory: 204.94 MB / 16.00 GB
  Shell: 5.8 - /bin/zsh
Binaries:
  Node: 16.15.0 - /usr/local/bin/node
  Yarn: 1.22.15 - ~/.npm-global/bin/yarn
  npm: 8.5.5 - /usr/local/bin/npm
```

**Comment by timhaywood** [comment]
It looks like this is endeed a line endings issue, the built file has CRLF line endings (windows) rather than LF. Can confirm the line endings on the file here: https://unpkg.com/create-bolt-cep@0.2.3/index.js

@justintaylor-dev I assume you're building on Windows, and not getting the error? I also got the error on macOS. 

Also wonder if this issue would better suited to [@hyperbrew/create-bolt-cep](https://github.com/hyperbrew/create-bolt-cep) repo?

## Solution

Should be able to output LF line endings by specifying the `newLine` TypeScript compiler option.

Pull request opened here: https://github.com/hyperbrew/create-bolt-cep/pull/1

**Comment by justintaylor-dev** [comment]
Thanks for the PR @timhaywood! https://github.com/hyperbrew/create-bolt-cep/pull/1

@fartinmartin Fix has been merged and should be working in 0.2.5, or next time you run `yarn create bolt-cep`

**Comment by fartinmartin** [comment]
Awesome, thank you both!

**Comment by justintaylor-dev** [comment]
@fartinmartin awesome to hear, glad to see people putting it to use!
