### ISSUE TITLE
TypeError: undefined is not an object

### ISSUE THREAD

**Issue by FlannelExpert** [hyperbrew/bolt-cep#38]
I've tried this with multiple builds but after a while of development I start to get this error alert "TypeError: undefined is not an object" whenever I try to run an evalEs function. Even when I revert back to the template jsxTest function.

**Comment by justintaylor-dev** [comment]
Which OS and App are you testing in?

**Comment by FlannelExpert** [comment]
Windows 11 in After Effects

**Comment by FlannelExpert** [comment]
A global function like...
`evalES(`alert("Hello from ExtendScript :: " + app.appName + " " + app.version)`, true)`
runs normally, but anytime I call a function in aeft.ts like...
`evalES(`helloWorld("${csi.getApplicationID()}")`)`
I get the TypeError.
Everything works fine for a little bit in the beginning but for some reason after some development I get that error. I've tried clearing everything and going back to scratch but still get the error, even on the helloWorld function.

**Comment by justintaylor-dev** [comment]
What is your `id` set to in `cep.config.ts` and what other config settings have you changed? Also what version of Node are you running (run `node -v`)

**Comment by FlannelExpert** [comment]
id: 'com.flannelexpert.gfxautomator'
Node: v16.17.1

The only other changes I've made were to displayName and panelDisplayName, both to 'GFX Automator'

**Comment by FlannelExpert** [comment]
I haven't had this issue in a while after starting a new project.

**Comment by gorlikariel** [comment]
@justintaylor-dev I'm getting the same error that @FlannelExpert was getting, not sure why this was closed, the bug is still out there.

Just like him, it just randomly hit me after a developing for a while. exact same issue, and I have no idea what causes it. 
Didn't change node versions, didn't touch cep.config.ts, just randomly started getting the "TypeError: undefined is not an object" error when trying to call evalEs. 

Would appreciate some help here, my development is completely stuck.

**Comment by justintaylor-dev** [comment]
@gorlikariel the issue was closed by the author, I assume because it was user error. If you're experiencing a similar issue, please open a new issue and list out your system specs and code snippets in JS and ExtendScript. Thanks
