### ISSUE TITLE
/settings/ and /panel/ cannot be found after `yarn dev`

### ISSUE THREAD

**Issue by JoshuaLelon** [hyperbrew/bolt-cep#51]
Hello,

I just created a new example project, following the below steps:

`yarn create bolt-cep myApp --template react`
`yarn`
`yarn dev`

and went to `http://localhost:3000/main/` which went fine:

![CleanShot 2023-02-05 at 12 02 55](https://user-images.githubusercontent.com/23615754/216836813-fdbadd77-afc0-4d05-8c02-fe30930399da.png)

But when I went to `/settings/` and `/panel` they don't appear to exist:

![CleanShot 2023-02-05 at 12 00 24](https://user-images.githubusercontent.com/23615754/216836739-fa8a1d97-3524-480c-ae2a-49c65eee5522.png)
![CleanShot 2023-02-05 at 12 01 04](https://user-images.githubusercontent.com/23615754/216836754-23031e74-4f51-4fe1-b0bf-e6579680d36b.png)

To be clear, it's possible that the reason is because those pages aren't implemented yet. I'm still learning the React / TypeScript and it's not obvious to me if that's why.

I'm opening this issue because the documentation seems to imply that those pages should be there by default:

![CleanShot 2023-02-05 at 12 03 41](https://user-images.githubusercontent.com/23615754/216836897-e74db6f6-312e-4a6f-a983-30d3a1f72381.png)

and they are not, at least not for me.

**Comment by justintaylor-dev** [comment]
Hi Joshua. Yes you'll need to create additional folders / html / JS files for each of those panels, otherwise they won't show up, see CEP panel structure for more details:

https://github.com/hyperbrew/bolt-cep/#cep-panel-structure

I'll add a note of this in the readme.

If you're interested in chatting on getting started with Bolt CEP, feel free to join our Discord: https://discord.gg/BjPYRKUq
