### ISSUE TITLE
Support different panel types

### ISSUE THREAD

**Issue by jameslockman** [hyperbrew/bolt-cep#69]
CEP Panels have several types. Is there a way to specify the type of panel in cep.cponfig.ts? Bridge, for instance, supports Embedded panels. This sits in the DispatchInfoList -> Extension -> DispatchInfo -> UI -> Type tag in the manifest.
![image](https://github.com/hyperbrew/bolt-cep/assets/2659225/27af56dc-d1af-43d7-b528-7a6bcb1563c9)

**Comment by justintaylor-dev** [comment]
Wasn't aware Bridge had a 5th option since just the 4 are listed in the [Cookbook](https://github.com/Adobe-CEP/CEP-Resources/blob/master/CEP_11.x/Documentation/CEP%2011.1%20HTML%20Extension%20Cookbook.md#extension-types)

![image](https://github.com/hyperbrew/bolt-cep/assets/10479769/be44054f-8cc7-4938-8480-bced772d5561)

Updated in `vite-cep-plugin` v 1.1.1 so you can update running `yarn add vite-cep-plugin`

**Comment by jameslockman** [comment]
Superb! Testing now.
