### ISSUE TITLE
Could not resolve "../cep/csinterface".

### ISSUE THREAD

**Issue by nemerem-x** [hyperbrew/bolt-cep#89]
Hi, I turned on my system today and when I ran "Yarn Build", I get:

`
vite v4.4.3 building for production...
`
`
✓ 18 modules transformed.
`
`
✓ built in 165ms
`
`
Could not resolve "../cep/csinterface" from "src/js/lib/utils/bolt.ts"
`
`
file: C:/.../panel/src/js/lib/utils/bolt.ts
`
`
error during build:
RollupError: Could not resolve "../cep/csinterface" from "src/js/lib/utils/bolt.ts"    
    at error (file:///C:/Users/Nemerem/Desktop/Coding/tech-pack/panel/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:2245:30)
    at ModuleLoader.handleInvalidResolvedId (file:///C:/Users/Nemerem/Desktop/Coding/tech-pack/panel/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24650:24)
    at file:///C:/Users/Nemerem/Desktop/Coding/tech-pack/panel/node_modules/vite/node_modules/rollup/dist/es/shared/node-entry.js:24612:26
error Command failed with exit code 1.
`

I removed node_module, package-lock.json and yarn.lock and re-added but no luck.

Dist Folder is empty.

Everything was working fine 2 days ago.

Thanks for the help.

**Comment by justintaylor-dev** [comment]
Sounds like csinterface.js was moved since it can't find it. This may have happened because you upgraded your `vite-cep-plugin`.

Make sure to follow the steps in "Update a Bolt CEP Project" in the readme:

https://github.com/hyperbrew/bolt-cep#misc-troubleshooting

If you still have issues with a fresh bolt install, feel free to re-open this issue, otherwise join our Discord for general help on using Bolt CEP: https://discord.gg/PC3EvvuRbc
